// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaterFlex.SaltMonitor.Infrastructure.Persistence;

#nullable disable

namespace WaterFlex.SaltMonitor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SaltMonitorDbContext))]
    [Migration("20260814031421_AddTelemetryHistoryRetention")]
    partial class AddTelemetryHistoryRetention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.CommissioningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ActivationAttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CreatedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ProvisionalCredentialId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TankDepthMm")
                        .HasColumnType("integer");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaterFlexWorkOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActivationAttemptId")
                        .IsUnique()
                        .HasFilter("\"ActivationAttemptId\" IS NOT NULL");

                    b.HasIndex("DealerId");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('PendingSensor', 'AwaitingFirstTelemetry')");

                    b.HasIndex("ProvisionalCredentialId");

                    b.HasIndex("TankId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('PendingSensor', 'AwaitingFirstTelemetry')");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("CommissioningSessions", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaterFlexCustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("WaterFlexCustomerId")
                        .IsUnique();

                    b.ToTable("CustomerAccounts", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Dealer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Dealers", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CommissionedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FactoryConfigurationVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FactoryFirmwareVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FactoryProvisionedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RetiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareId")
                        .IsUnique();

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceBootstrapCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("\"RevokedAtUtc\" IS NULL AND \"ConsumedAtUtc\" IS NULL");

                    b.ToTable("DeviceBootstrapCredentials", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceCredentials", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("InstalledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstalledBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RemovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TankId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaterFlexWorkOrderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasFilter("\"RemovedAtUtc\" IS NULL");

                    b.HasIndex("TankId")
                        .IsUnique()
                        .HasFilter("\"RemovedAtUtc\" IS NULL");

                    b.ToTable("DeviceInstallations", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.ProvisioningAuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("CommissioningSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CommissioningSessionId", "OccurredAtUtc");

                    b.HasIndex("DeviceId", "OccurredAtUtc");

                    b.ToTable("ProvisioningAuditEvents", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.ServiceLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaterFlexLocationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId", "WaterFlexLocationId")
                        .IsUnique();

                    b.ToTable("ServiceLocations", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Tank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CapacityPounds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ServiceLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("WaterFlexAssetId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceLocationId");

                    b.ToTable("Tanks", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TankCalibrationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CommissioningDistanceMm")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("DeviceInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TankDepthMm")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceInstallationId")
                        .IsUnique()
                        .HasFilter("\"EffectiveToUtc\" IS NULL");

                    b.HasIndex("DeviceInstallationId", "Version")
                        .IsUnique();

                    b.ToTable("TankCalibrations", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryDailySummary", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<double>("FillPercentAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("FillPercentLatest")
                        .HasColumnType("double precision");

                    b.Property<double>("FillPercentMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FillPercentMin")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastReadingAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestFirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("RawDistanceMmAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("RawDistanceMmMax")
                        .HasColumnType("integer");

                    b.Property<int>("RawDistanceMmMin")
                        .HasColumnType("integer");

                    b.Property<long>("ReadingCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WifiRssiDbmAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("WifiRssiDbmMax")
                        .HasColumnType("integer");

                    b.Property<int>("WifiRssiDbmMin")
                        .HasColumnType("integer");

                    b.Property<int>("WorstQuality")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId", "BucketStartUtc");

                    b.HasIndex("BucketStartUtc");

                    b.ToTable("TelemetryDailySummaries", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryHourlySummary", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BucketStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("bigint");

                    b.Property<double>("FillPercentAverage")
                        .HasColumnType("double precision");

                    b.Property<double>("FillPercentLatest")
                        .HasColumnType("double precision");

                    b.Property<double>("FillPercentMax")
                        .HasColumnType("double precision");

                    b.Property<double>("FillPercentMin")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("LastReadingAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestFirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("RawDistanceMmAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("RawDistanceMmMax")
                        .HasColumnType("integer");

                    b.Property<int>("RawDistanceMmMin")
                        .HasColumnType("integer");

                    b.Property<long>("ReadingCount")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WifiRssiDbmAverage")
                        .HasColumnType("double precision");

                    b.Property<int>("WifiRssiDbmMax")
                        .HasColumnType("integer");

                    b.Property<int>("WifiRssiDbmMin")
                        .HasColumnType("integer");

                    b.Property<int>("WorstQuality")
                        .HasColumnType("integer");

                    b.HasKey("DeviceId", "BucketStartUtc");

                    b.HasIndex("BucketStartUtc");

                    b.ToTable("TelemetryHourlySummaries", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryMaintenanceState", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("TelemetryMaintenanceStates", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryReadingRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("BootId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceInstallationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorFlagsJson")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<double>("FillPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quality")
                        .HasColumnType("integer");

                    b.Property<int>("RawDistanceMm")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TankCalibrationRecordId")
                        .HasColumnType("uuid");

                    b.Property<long>("UptimeMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("WifiRssiDbm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TankCalibrationRecordId");

                    b.HasIndex("DeviceInstallationId", "ReceivedAtUtc");

                    b.HasIndex("DeviceId", "BootId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("DeviceId", "ReceivedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("TelemetryReadings", (string)null);
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.CommissioningSession", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany("CommissioningSessions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceCredential", "ProvisionalCredential")
                        .WithMany()
                        .HasForeignKey("ProvisionalCredentialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Tank", "Tank")
                        .WithMany()
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Device");

                    b.Navigation("ProvisionalCredential");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceBootstrapCredential", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany("BootstrapCredentials")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceCredential", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany("Credentials")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceInstallation", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Dealer", "Dealer")
                        .WithMany("Installations")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany("Installations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Tank", "Tank")
                        .WithMany("Installations")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Device");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.ProvisioningAuditEvent", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.CommissioningSession", "CommissioningSession")
                        .WithMany("AuditEvents")
                        .HasForeignKey("CommissioningSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissioningSession");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.ServiceLocation", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.CustomerAccount", "CustomerAccount")
                        .WithMany("ServiceLocations")
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerAccount");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Tank", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.ServiceLocation", "ServiceLocation")
                        .WithMany("Tanks")
                        .HasForeignKey("ServiceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceLocation");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TankCalibrationRecord", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceInstallation", "DeviceInstallation")
                        .WithMany("Calibrations")
                        .HasForeignKey("DeviceInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceInstallation");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryDailySummary", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryHourlySummary", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.TelemetryReadingRecord", b =>
                {
                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceInstallation", "DeviceInstallation")
                        .WithMany()
                        .HasForeignKey("DeviceInstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WaterFlex.SaltMonitor.Infrastructure.Persistence.TankCalibrationRecord", "TankCalibrationRecord")
                        .WithMany()
                        .HasForeignKey("TankCalibrationRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("DeviceInstallation");

                    b.Navigation("TankCalibrationRecord");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.CommissioningSession", b =>
                {
                    b.Navigation("AuditEvents");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.CustomerAccount", b =>
                {
                    b.Navigation("ServiceLocations");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Dealer", b =>
                {
                    b.Navigation("Installations");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Device", b =>
                {
                    b.Navigation("BootstrapCredentials");

                    b.Navigation("CommissioningSessions");

                    b.Navigation("Credentials");

                    b.Navigation("Installations");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.DeviceInstallation", b =>
                {
                    b.Navigation("Calibrations");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.ServiceLocation", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("WaterFlex.SaltMonitor.Infrastructure.Persistence.Tank", b =>
                {
                    b.Navigation("Installations");
                });
#pragma warning restore 612, 618
        }
    }
}
