FROM mcr.microsoft.com/dotnet/sdk:10.0.300@sha256:c0790639332692a0d56cdd81ed581cfd24d040d9839764c138994866df89a3b6 AS build
WORKDIR /src

COPY ["NuGet.Config", "./"]
COPY ["global.json", "./"]
COPY ["backend", "backend/"]

RUN dotnet restore backend/WaterFlex.SaltMonitor.slnx --configfile NuGet.Config

RUN dotnet publish backend/src/WaterFlex.SaltMonitor.Worker/WaterFlex.SaltMonitor.Worker.csproj \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:10.0@sha256:a365ce6a50b09176855d085c69da3fc1204a48432e36087e9a208f6e5860e235
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends libgssapi-krb5-2 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .

USER $APP_UID

ENTRYPOINT ["dotnet", "WaterFlex.SaltMonitor.Worker.dll"]
