<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.103.4" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.100.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../WaterFlex.SaltMonitor.Domain/WaterFlex.SaltMonitor.Domain.csproj" />
    <ProjectReference Include="../WaterFlex.SaltMonitor.Infrastructure/WaterFlex.SaltMonitor.Infrastructure.csproj" />
    <ProjectReference Include="../WaterFlex.SaltMonitor.Rules/WaterFlex.SaltMonitor.Rules.csproj" />
    <ProjectReference Include="../WaterFlex.SaltMonitor.Ingestion/WaterFlex.SaltMonitor.Ingestion.csproj" />
  </ItemGroup>
</Project>
